2021-10-29 15:51:18,131 - [test_login.py-->line:31] - INFO:用例---[登录成功]----执行成功
2021-10-29 15:51:18,180 - [test_login.py-->line:31] - INFO:用例---[账号为空]----执行成功
2021-10-29 15:51:18,222 - [test_login.py-->line:31] - INFO:用例---[密码为空]----执行成功
2021-10-29 15:51:18,265 - [test_login.py-->line:31] - INFO:用例---[密码错误]----执行成功
2021-10-29 15:51:18,325 - [test_regsiter.py-->line:29] - INFO:用例---[注册成功]----执行通过
2021-10-29 15:51:18,371 - [test_regsiter.py-->line:24] - ERROR:用例---[账户已存在]----执行失败
2021-10-29 15:51:18,371 - [test_regsiter.py-->line:25] - ERROR:{'code': 0, 'msg': '账户已存在'} != {'code': 1, 'msg': '注册成功'}
- {'code': 0, 'msg': '账户已存在'}
?          ^          ^^^^^

+ {'code': 1, 'msg': '注册成功'}
?          ^          ^^^^
Traceback (most recent call last):
  File "F:\pythonlearn\Real_python_project\testcases\test_regsiter.py", line 21, in test_regsiter
    self.assertEqual(excepted, res)
  File "F:\Python\lib\unittest\case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "F:\Python\lib\unittest\case.py", line 1130, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "F:\Python\lib\unittest\case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: {'code': 0, 'msg': '账户已存在'} != {'code': 1, 'msg': '注册成功'}
- {'code': 0, 'msg': '账户已存在'}
?          ^          ^^^^^

+ {'code': 1, 'msg': '注册成功'}
?          ^          ^^^^

2021-10-29 15:51:18,423 - [test_regsiter.py-->line:29] - INFO:用例---[两次密码不一致]----执行通过
2021-10-29 15:51:18,476 - [test_regsiter.py-->line:29] - INFO:用例---[密码必须在6-18位之间]----执行通过
2021-10-29 15:51:18,527 - [test_regsiter.py-->line:29] - INFO:用例---[所有参数不能为空]----执行通过
